//
//  gnomics.swift
//  BookOfHours
//
//  Created by Gabriel Getzie on 12/30/24.
//

import Foundation

let gnomics: [String] = [
    "Try slowing it down",
    "Try speeding it up",
    "Try pausing it",
    "Try looping it",
    "Try repeating it",
    "Try reversing it",
    "Try reordering it",
    "Try it chronologically",
    "Try it asynchronously",
    "Try doing it out of sync",
    "Try it simultaneously",
    "Try it concurrently",
    "Try it incrementally ",
    "Try staggering it",
    "Try doing it backward",
    "Try bypassing is",
    "Try interrupting it",
    "Try extending it",
    "Try freezing it",
    "Try continuing it",
    "Try discontinuing it",
    "Try it for 1 hour.",
    "Try abruptly halting it",
    "Try it out of order",
    "Try not repeating it",
    "Try it in the future",
    "Try it now",
    "Try making it a series",
    "Try it once; never repeat",
    "Try interrupting it",
    "Try it again",
    "Try counting the seconds",
    "Try counting the seconds backward",
    "Try feeling time",
    "Try ignoring the clock",
    "Don’t wear a watch",
    "Don’t look at your phone for the time",
    "Try wearing a watch",
    "Try not keeping pace",
    "Try alternating it back and forth",
    "Try imagining how it will be understood in the future",
    "Try imagining how it would have been understood in the past",
    "Try imagining how it will be received in the present",
    "Try turning wasted time into creative time",
    "Try wasting time",
    "Try wasting 5 minutes",
    "Try wasting an afternoon",
    "Try wasting a day",
    "Try taking time",
    "Try removing time from the equation",
    "Try multiplying it",
    "Try thinking about it in the present moment",
    "Try keeping it steady",
    "Try to not replicate it",
    "Try to replicate it",
    "Try arriving early",
    "Try arriving 1 second late",
    "Try arriving precisely",
    "Try it earlier",
    "Try it later",
    "Try it in the future",
    "Try it now",
    "Try it in the present",
    "Remember when __",
    "Try forgetting it",
    "Try remembering it",
    "Try culling the timeline",
    "Try cluttering the timeline",
    "Try being in it for a moment",
    "It’s in the past",
    "It’s in the present",
    "It’s in the future",
    "Return to the beginning",
    "Repeat the process",
    "Do it again",
    "Return exactly as you came",
    "Return to where you started from, but use a different route",
    "Try repeating with only a slight alteration",
    "Give it another try",
    "Give it 19 minutes",
    "Give away 19 minutes",
    "Keep pace",
    "Sporadic ",
    "What if you could redo it?",
    "What if ___?",
    "What if ___ happened, how would it be different? ",
    "What if ___ happened, how would the past be different? ",
    "What if ___ happened, how would the present be different? ",
    "What if ___ happened, how might the future be different? ",
    "In a different time",
    "Step out of pace",
    "Step out of time",
    "Step in time",
    "What are you thinking about right now?",
    "What were you thinking about 1 minute ago?",
    "What were you thinking about 5 minutes ago?",
    "What were you thinking about 19 minutes ago?",
    "What were you thinking about yesterday?",
    "What were you thinking about last season?",
    "What were you thinking about last year?",
    "What will you be thinking about in 1 minute?",
    "What will you be thinking about in 5 minutes?",
    "What will you be thinking about in 19 minutes?",
    "What will you be thinking about tomorrow?",
    "What will you be thinking about next season?",
    "What will you be thinking about in a year?",
    "Casual time",
    "Formal time",
    "Discarded time",
    "Disciplined time",
    "Unstructured time",
    "Rigorously timed",
    "Empty time",
    "Full time",
    "Unappreciated time",
    "Simultaneous events",
    "Theoretical time",
    "Constantly",
    "Unending time | Time Unending",
    "Constant time",
    "Absolute time",
    "Flat time",
    "Sharp time",
    "Divide time",
    "Transition time",
    "Ambiguous time",
    "Specific time",
    "Actual time",
    "Real time",
    "Simulated time",
    "Measured time",
    "Fictional time",
    "Novel time",
    "Reading time",
    "Study time",
    "Forgotten time",
    "Precious time",
    "Golden hour",
    "Ranked time",
    "Used time",
    "Unequal time",
    "People time",
    "Alone time",
    "Recharging time",
    "Sleep time",
    "Economics of time",
    "Unsanctioned time",
    "Approved time",
    "Overtime",
    "Inside time",
    "Outside time",
    "Up time",
    "Down time",
    "Thinking time",
    "Relaxing time",
    "Capture time",
    "Creative time",
    "Donate time",
    "Destroy time",
    "Remove time",
    "Disconnect from the present",
    "Disconnect from the past",
    "Disconnect from the future",
    "Disconnect from the moment",
    "Discover time ",
    "Prescribe time",
    "Delineate time",
    "Abandon time",
    "Restrain time",
    "Leave time",
    "Forsake time",
    "Vacate time",
    "Broken time",
    "Silent time",
    "Quiet time",
    "Peaceful time",
    "Chaotic time",
    "Cancel time",
    "Stop time",
    "Halt time",
    "Balanced time",
    "Equal time",
    "First time",
    "Second time",
    "Final time",
    "Last time",
    "Anchored time",
    "Valuable time",
    "Nothing time",
    "Important time",
    "Destructive time",
    "Cliché time",
    "Fright time",
    "Scary time",
    "Happy time ",
    "Calm time",
    "Layered time ",
    "Deposited time",
    "Lumped time",
    "Adding time",
    "Subtracting time",
    "Accruing time",
    "Increasing time",
    "Crediting time",
    "Donating time",
    "Giving time",
    "Doing time",
    "Cut time",
    "Vital time",
    "Connecting time",
    "Removal time",
    "Frivolous time",
    "Minimal time",
    "Looping calm",
    "Looping cliches",
    "Incorporate ",
    "Timely, but not prescient",
    "Suddenly",
    "Quickly",
    "Rapidly",
    "Gradually",
    "Swiftly",
    "Speedily",
    "Promptly",
    "Expeditiously",
    "Precipitously",
    "Instantly",
    "Immediately",
    "Slowly",
    "In a flash",
    "On the double",
    "Hastily",
    "Fleetingly",
    "Momentarily",
    "Passingly",
    "Transiently",
    "Briskly",
    "Alacrity",
    "Impulsively",
    "Backtrack",
    "Backpedal",
    "Double back",
    "Come again",
    "Go back",
    "Revisit",
    "Reverse",
    "Repeat",
    "Loop",
    "Circle around it",
    "Reverse flow",
    "Backwards",
    "Make future plans, break them",
    "Make future plans, follow through",
    "Make future plans, but arrive late",
    "Recall",
    "Recollect",
    "Recollect, but change something",
    "Suspend the idea in the moment",
    "Try eliminating past clutter",
    "Reverse course",
    "Forget, remember later",
    "Retrace",
    "Advance",
    "Move forward",
    "Take a detour",
    "It should be, but it is not.",
    "It could be, but it isn’t (yet).",
    "It will be, soon.",
    "It will be, eventually.",
    "When will you work on it?",
    "Duplicate",
    "Triplicate",
    "Double",
    "Tripple",
    "Déjà vu",
    "Repeat",
    "Try capturing time",
    "Progressively",
    "Regularly",
    "Increasingly",
    "Steadily",
    "Bit by bit",
    "Step by step",
    "Little by little",
    "In stages",
    "Recurrently ",
    "Rarely",
    "Evenly",
    "Systematically",
    "Steadily",
    "Unevenly",
    "Irregularly",
    "Repeatedly",
    "Often",
    "Methodically",
    "Delay",
    "Unanticipated",
    "Multiply",
    "Time removed",
    "Time connected",
    "Time deposits",
    "Time lumps",
    "Time bumps",
    "Time growth",
    "Time added",
    "Time subtracted",
    "Time accrued",
    "Time increased",
    "Time credit",
    "Time Layers",
    "Time breaks",
    "Time toss",
    "Time expensed",
    "Time used",
    "Time suck",
    "Time echoes",
    "Time flows",
    "Time streams",
    "Time currents",
    "Time floods",
    "Time gushes",
    "Time surges",
    "Time rolls ",
    "Time drifts",
    "Time courses",
    "Time pours",
    "Time tides",
    "Time arises",
    "Time issues",
    "Time springs up",
    "Time spills over",
    "Time swells",
    "Time subsides",
    "Time freezes",
    "Time warps",
    "Time bursts",
    "Time develops",
    "Time disappears",
    "Time recoils",
    "Time brims",
    "Time forms",
    "Time emerges ",
    "Time emerges in __",
    "Time emerges from __",
    "Time emanates in __",
    "Time emanates from __",
    "Time emanates ",
    "Timeout",
    "Time in",
    "Time synchronization",
    "Time unappreciated",
    "Time fill",
    "Try going backward",
    "Try a short cut",
    "Try thinking about the future",
    "Enforce free time",
    "Break time",
    "Free time",
    "Work time",
    "Play time",
    "Eat time",
    "Eating time",
    "Stealing time",
    "Write for 4 minutes without stopping",
    "Make it fast, and then abruptly slow",
    "Make it slow, and then abruptly fast",
    "Make more of your time",
    "Use time wisely",
    "Time is a limited edition",
    "How you use your time is how you value it.",
    "Make more time",
    "Don’t think about the past for 30 seconds",
    "Imagine the future",
    "One thing at a time",
    "Past",
    "Present",
    "Future",
    "Contemporary",
    "Contemporaneous",
    "Concurrent",
    "Think about it from a different era",
    "Think about it as if it you were looking at the present from 10 years in the future",
    "Try again in a week",
    "Make the end the beginning",
    "Make the beginning the end",
    "Focus on each second.",
    "Focus on it for 19 seconds",
    "Focus on it for 19 minutes",
    "Do something for 5 minutes; repeat it at the same time tomorrow",
    "Make a list of everything you did in the past hour. Repeat nothing on the list during the next hour.",
    "Make a list of everything you did in the past hour. Repeat everything on the list during the next hour.",
    "Make a list of everything you did in the past hour. Repeat only one item on the list in the next hour.",
    "Make a list of everything you did yesterday. Do the same thing today.",
    "Make a list of everything you did before noon. Repeat in the afternoon.",
    "Make a list of everything you did yesterday. Repeat nothing.",
    "Make a list of everything you did yesterday. Repeat only 2 things.",
    "Make a list of everything you did before noon. Do not repeat in the afternoon.",
    "Do something you enjoy for 50 minutes",
    "Focus on the details for 19 minutes",
    "Try making a list of everything you did in the past hour",
    "everything you do within 1 hour ",
    "everything you do within 1 hour",
    "The present is the past",
    "How do you spend your time?",
    "What if time was saved?",
    "Can time be ‘saved’?",
    "If you could go back in time, how would you have done it differently?",
    "What if a week had 8 days? ",
    "What if the present were the past?",
    "What if it is from a different generation?",
    "Measure time by your friend’s footsteps",
    "Measure time by your heartbeat",
    "Jump out of the moment",
    "Jump back 5 minutes",
    "Skip ahead 5 minutes",
    "What color is time?",
    "Extend the moment",
    "Pause at the next turn",
    "Out of sync",
    "Repeat an error",
    "Abruptly change what you are doing",
    "Discontinue it shortly",
    "Discontinue it abruptly",
    "Discontinue it gradually",
    "Discontinue it quickly",
    "Repeat the past 5 minutes",
    "Can you hide time?",
    "How long was it hidden?",
    "What if it happened in a different era?",
    "Try a new speed",
    "Slowly turn around",
    "Echoes from the past",
    "Time is linear? | Time is linear. | Time is linear! | Time is linear…",
    "Time passes? | Time passes. | Time passes! | Time passes…",
    "Time moves? | Time moves. | Time moves! | Time moves…",
    "Time loops? | Time loops. | Time loops! | Time loops…",
    "Free time? | Free time. | Free time! | Free time…",
    "Begin. Repeat. Again. Back to the beginning. End.",
    "End. Back to the beginning. Repeat. Again.",
    "Regimented seconds, minutes, hours, days, weeks, months, years.",
    "Unscheduled time.",
    "Overscheduled time.",
    "Overbooked | Underbooked",
    "Overscheduled | Underscheduled",
    "Minutes are slow.",
    "Hours are fast.",
    "Instantaneously",
    "Bring the ending forward.",
    "Push the beginning back.",
]
