//
//  jokes.swift
//  BookOfHours
//
//  Created by Gabriel Getzie on 12/30/24.
//

import Foundation

let jokes: [String] = [
    // jokes from https://www.menshealth.com/trending-news/a34437277/best-dad-jokes/
    "What does a baby computer call his father? Data.",
    "After an unsuccessful harvest, why did the farmer decide to try a career in music? Because he had a ton of sick beets.",
    "I only seem to get sick on weekdays. I must have a weekend immune system. ",
    "My friend was showing me his tool shed and pointed to a ladder. “That's my stepladder,” he said. \"I never knew my real ladder.\"",
    "What do you call a Frenchman wearing sandals? Philippe Flop.",
    "Why is it so cheap to throw a party at a haunted house? Because the ghosts bring all the boos. ",
    "I don’t get why Marvel doesn’t use the Hulk to advertise more. He’s basically one big Banner. ",
    "What brand of underwear do scientists wear? Kelvin Klein. ",
    "Which days are the strongest? Saturday and Sunday. The rest are weekdays.",
    "I just found out I’m colorblind. The news came out of the purple!",
    "Did you know your pupils are the last part to stop working when you die? They dilate. ",
    "My wife asked me the other day where I got so much candy. I said, \"I always have a few Twix up my sleeve.\"",
    "How do cows stay up to date? They read the Moo-spaper. ",
    "What's the difference between a well-dressed man on a unicycle and a poorly-dressed man on a bicycle? Attire.",
    "I hate my job—all I do is crush cans all day. It’s soda pressing.",
    "Where do pirates get their hooks? Second hand stores.",
    "Of all the inventions of the last 100 years, the dry erase board has to be the most remarkable.",
    " In America, using the metric system can get you in legal trouble. ",
    "What do you call a line of men waiting to get haircuts? A barberqueue. ",
    "In fact, if you sneer at any other method of measuring liquids, you may be held in contempt of quart.",
    "Who were the greenest Presidents in US history? The bushes.",
    "My hotel tried to charge me ten dollars extra for air conditioning. That wasn’t cool.",
    "What do you call a beehive without an exit? Unbelievable.",
    " If I ever find the doctor who screwed up my limb replacement surgery…I’ll kill him with my bear hands.",
    "Did you know that the first french fries weren’t cooked in France? They were cooked in Greece.",
    "This morning, Siri said, “Don’t call me Shirley.” I accidentally left my phone in Airplane mode.",
    "It's easy to convince ladies not to eat Tide Pods, but harder to deter gents. ",
    "I asked my date to meet me at the gym but she never showed up. I guess the two of us aren't going to work out.",
    "How do you find Will Smith in a snowstorm? You look for fresh prints. ",
    "The difference between a numerator and a denominator is a short line. Only a fraction of people will understand this.",
    "I found a wooden shoe in my toilet today. It was clogged.",
    "I just broke up with my mathematician girlfriend. She was obsessed with an X. ",
    "I can't take my dog to the pond anymore because the ducks keep attacking him. That's what I get for buying a pure bread dog.",
    "To whoever stole my copy of Microsoft Office, I will find you. You have my Word. ",
    "What’s Forrest Gump’s password? 1forrest1.",
    "I used to run a dating service for chickens. But I was struggling to make hens meet.",
    "If prisoners could take their own mug shots…They’d be called cellfies.",
    "Have you heard about those new corduroy pillows? They're making headlines.",
    "If a pig loses its voice…does it become disgruntled?",
    "Wanna hear a joke about paper? Never mind. It's tearable.",
    "A panic-stricken man explained to his doctor, “You have to help me, I think I’m shrinking.” “Now settle down,” the doctor calmly told him. “You'll just have to learn to be a little patient.”",
    "What do you call a bundle of hay in a church? Christian Bale.",
    "A ship carrying red paint and a ship carrying blue paint collide in the middle of the ocean. Both crews were marooned.",
    "What is a guitar player's favorite Italian food? Strum-boli.",
    "How does cereal pay its bills? With Chex.",
    "Have you heard about the restaurant on the moon? Great food, no atmosphere.",
    "I don't trust stairs. They're always up to something.",
    "People in Athens rarely get up before sunrise. Dawn is tough on Greece. ",
    "Why'd the alternate universe Spider-Man do so well on his driving test? He's an excellent parallel Parker. ",
    "Never date a tennis player. Love means nothing to them. ",
    "What's a lawyer's favorite drink? Subpoena colada. ",
    "What did Yoda say when he saw himself in 4K? HDMI. ",
    "What do you call a wizard who's really bad at football? Fumbledore. ",
    "How do nonbinary people hurt each other? They slash them. (They/them) ",
    "I used to hate facial hair, but then it grew on me.",
    "What's blue and not very heavy? Light blue. ",
    "I don't get why bakers aren't wealthier. They make so much dough. ",
    "I asked my wife if I was the only one she slept with. She said yes—the others were 7’s and 8’s. ",
    "How do you make a tissue dance? You put a little boogie in it.",
    "How do flat-earthers travel? On a plane.",
    "I ordered a chicken and an egg from Amazon. I'll let you know. ",
    "Imagine if you walked into a bar and there was a long line of people waiting to take a swing at you. That’s the punch line.",
    "My wife left me because of my obsession with pasta. I'm feeling cannelloni right now. ",
    "What’s an astronaut’s favorite part of the computer? The Space Bar.  ",
    "I was playing chess with my friend and he said, “Let’s make this interesting.” So we stopped playing chess.",
    "I was in a job interview the other day and they asked if I could perform under pressure. I said no, but I could perform Bohemian Rhapsody. ",
    "Why didn't the vampire attack Taylor Swift? She had bad blood. ",
    "Today I’m attaching a light to the ceiling, but I’m afraid I’ll probably screw it up. ",
    "I hate it when people say age is only a number. Age is clearly a word.",
    "I can't take my dog to the pond anymore because the ducks keep attacking him. That's what I get for buying a pure bread dog.",
    "Someone complimented my parking today! They left a sweet note on my windshield that said “parking fine.”",
    "I was excited to hear Apple might start selling its own cars until I learned they wouldn’t support windows. ",
    "I just applied for a job down at the diner. I told them I really bring a lot to the table. ",
    "\"Cop: I'm arresting you for downloading the entire Wikipedia.\" Man: \"Wait! I can explain everything!\"",
    "My friend couldn't afford to pay his bill, so I sent him a \"Get Well Soon\" card.",
    "I'm Buzz Aldrin, second man to step on the moon. Neil before me. ",
    "Why was 2019 afraid of 2020? Because they had a fight and 2021. ",
    "Did you hear Bruce Springsteen changed the lyrics to one of his songs? What’s he going to change next—his hair? His clothes? His face?",
    "This year’s Fibonacci convention is going to be really special. Apparently it’s as big as the last two put together. ",
    "An apple a day keeps the doctor away. At least it does if you throw it hard enough.",
    "I’m addicted to collecting vintage Beatles albums. I need Help.",
    "In 2017 I didn't do a marathon. I didn't do one in 2018, 2019, or 2020, either. This is a running joke. ",
    "Not to brag but I made six figures last year. I was also named worst employee at the toy factory. ",
    "Ever since we started quarantining, I've only been telling inside jokes. ",
    "If you're feeling depressed, try drinking a gallon of water before you go to sleep. It'll give you a reason to get out of bed in the morning. ",
    "My landlord told me we need to talk about the heating bill. \"Sure,\" I said. \"My door is always open.\"",
    "I built a model of Mount Everest and my son asked if it was to scale. \"No,\" I said. \"It's to look at.\" ",
    "What has five toes and isn't your foot? My foot. ",
    "My friend claims he glued himself to his autobiography. I don't believe him, but that's his story and he's sticking to it. ",
    "When I was a kid, my mother told me I could be anyone I wanted to be. Turns out, identity theft is a crime.",
    " What's brown and sticky? A stick.",
    "My doctor told me I was going deaf. The news was hard for me to hear. ",
    "A century ago, two brothers decided it was possible to fly. And as you can see, they were Wright. ",
    "I'm reading a horror story in braille. Something bad is going to happen, I can just feel it.",
    "Anyone looking to buy a Delorean? Good shape, good mileage. Only driven from time to time.",
    "During my calculus test, I had to sit between identical twins. It was hard to differentiate between them. ",
    "Does anybody know where a guy can find a person to hang out with, talk to, and enjoy spending time with? I'm just asking for a friend.",
    "Why did the Invisible Man turn down a job offer? He couldn’t see himself doing it.",
    "When I die, I want to be cremated. It’s my last chance to have a smokin’ hot body.",
    "“Just say NO to drugs!” Well, if I’m talking to drugs, I probably already said yes.",
    "I once saw a one-handed man in a second-hand store. I told him, “I don’t think they have what you’re looking for, sir.”",
    "What do you call a sad cup of coffee? Depresso.",
    "What did one monocle say to the other monocle? Let's get together and make a spectacle of ourselves. ",
    "How come the Hulk doesn't lose his pants when he transforms? The experiment altered his jeans. ",
    "I didn't want to believe that my dad was stealing from his job as a traffic cop, but when I got home, all the signs were there. ",
    "I just spent $300 on a limo and learned it doesn't come with a driver. I can't believe I have nothing to chauffer it. ",
    "What’s green and has wheels? Grass. I lied about the wheels.",
    " I have a joke about trickle down economics. But 99% of you will never get it.",
    "Just got back from a job interview where I was asked if I could perform under pressure. I said I wasn’t too sure about that but I could do a wicked “Bohemian Rhapsody.”",
    "What’s the best thing about living in Switzerland? I don’t know, but the flag is a big plus.",
    "At the job interview, they asked me, “Where do you see yourself in five years?”I told him, “I think we’ll still be using mirrors in five years.” ",
    "A buddy asked how many fish I caught. I told him it’s not polite to fish and tell. ",
    "How many clickbait articles does it take to change a lightbulb? The answer will shock you! ",
    "How do you make a water bed bouncier? Add spring water. ",
    "I always knock on the fridge door before opening it, just in case there's a salad dressing. ",
    "Where do dads store their dad jokes? In the dad-a-base. ",
    "What kind of fruit do ghosts like? Boo-berries. ",
    "I tried to start a professional hide and seek team, but it didn't work out. Turns out, good players are hard to find. ",
    "Women should not have children after 36—really, 36 children is enough. ",
    "What happens when frogs park illegally? They get toad.",
    "Lance isn't that common a name these days, but in medieval times, they were called lance-a-lot. ",
    "I had an appointment to see my psychic next week, but she just called to cancel.She said I won’t be able to make it.",
    "I used to be addicted to soap, but I’m clean now. ",
    "I wanted my kids to watch the orchestra, but I had to turn it off—too much sax and violins. ",
    "A cop started crying while he was writing me a ticket. I asked him why and he said, \"It's a moving violation.\"",
    "Swords will never go obsolete. They're cutting edge technology. ",
    "I asked the IT guy, \"How do you make a Motherboard?\" He said, \"I tell her about my job.\"",
    "What do you call it when James Bond takes a bath? Bubble 07. ",
    "30 percent of pet owners let their pets sleep in their bed. I tried it and my goldfish died. ",
    "What is the difference between a literalist and a kleptomaniac?",
    "I just found out Albert Einstein existed. My whole life I thought he was a theoretical physicist.A comma. A literalist takes everything literally. A kleptomaniac takes everything, literally.",
    "You used to be able to get air for free at gas stations, but now it's a $1. That's inflation for you. ",
    "My dad was born a conjoined twin, but separated at birth. So I have an uncle, once removed. ",
    "Why is it a bad idea to eat a clock? Because it's so time-consuming. ",
    "I went to a smoke shop only to discover it’d been replaced by an apparel store.Clothes, but no cigar. ",
    "Why should you never brush your teeth with your left hand? Because a toothbrush works better.",
    "My grief counselor died the other day. He was so good at his job, I don’t even care.",
    " Give a man a plane ticket and he flies for the day. Push him out of the plane at 3,000 feet and he’ll fly for the rest of his life.",
    "As I get older, I remember all the people I lost along the way. Maybe a career as a tour guide was not the right choice. ",
    "I was reading a great book about an immortal dog the other day. It was impossible to put down.",
    "What do you call someone who refuses to fart in public? A private tutor.",
    "I just read that someone in London gets stabbed every 52 seconds. Poor bastard.",
    "They say that breakfast is the most important meal of the day. Well, not if it’s poisoned. Then the antidote becomes the most important.",
    "The guy who stole my diary just died. My thoughts are with his family. ",
    "Do you know the last thing my grandfather said to me before he kicked the bucket? “Grandson, watch how far I can kick this bucket.”",
    "If you donate a kidney, everybody loves you and you’re a total hero. But try donating five kidneys and suddenly everyone is yelling and the police get called.",
    " I have a fish that can breakdance. Only for ten seconds though, and only once.",
    "My friend said that if he went off a cliff, it would be on his own accord. It’s a good thing he drives a Civic.",
    " In my free time, I like to help blind people. Verb, not adjective. ",
    "A doctor walks into a room with a dying patient and tells him, “I’m sorry, but you only have ten left.” The patient asks him, “Ten what, Doc? Hours? Days? Weeks?” The doctor calmly looks at him and says, “Nine.”",
    "I like to spend my weekends playing chess with elderly men in the park. But it’s becoming more difficult. You try finding exactly32 old guys. ",
    "What do you call bears with no ears? B. ",
    "What’s the difference between a wizard who raises the undead and a sexy vampire? One is a necromancer and the other is a neck romancer. ",
    "A man walks into a magic forest and tries to cut down a talking tree. “You can't cut me down,” the tree complains. “I’m a talking tree!” The man responds, “You may be a talking tree, but you will dialogue.” ",
    "I heard Sony’s coming out with a new console during the pandemic...It’s called the Plaguestation 5.",
    "When my uncle Frank died, he wanted his remains to be buried in his favorite beer mug. His last wish was to be Frank in Stein. ",
    "A man walks into a bar. The bartender asks, \"What do you want?\" The man says, \"Oh, just some fruit punch.\" The bartender sighs and shakes his head, \"If you want punch, you're gonna have to wait in line.\" The man looks around, but there is no punchline.",
    "What’s worse than biting into an apple and finding a worm? Biting into an apple and finding half a worm. ",
    "I just got my doctor's test results and I’m really upset. Turns out, I’m not gonna be a doctor.",
    "I think my wife is putting glue on my antique guns collection. She denies it but I'm sticking to my guns.",
    "My wife left a note on the fridge that said, “This isn't working.” I’m not sure what she’s talking about. I opened the fridge door and it’s working fine!",
    "My wife wanted to spice up our sex life, so she asked if we could play doctor tonight. It seemed like a weird idea, but I’m eager to please. ",
    "My wife told me she didn't understand cloning. I told her, \"That makes two of us.\" ",
    "My wife told me she’ll slam my head on the keyboard if I don't get off the computer. I’m not too worried, I think she’s jokinlkjhfakljn m,.nbziyoao78yv87dfaoyuofaytdf",
    "My wife gave birth three times and still fits in her prom dress from high school. I gave birth zero times and I don’t fit in my pants from March.",
    "When I see the names of lovers engraved on a tree, I don’t find it cute or romantic. I find it weird how many people take knives with them on dates.",
    "After dinner my wife asked if I could clear the table. I needed a running start, but I made it. ",
    "Why didn’t the astronaut come home to his wife? He needed his space.",
    "My wife gave me an ultimatum: Her or my addiction to sweets. The decision was a piece of cake. ",
    "My wife told me to quit doing my terrible Arnold impression, but don't worry, I'll return. ",
    "“Just look at that couple down the road,” a wife told her husband. “He keeps holding her hand, kissing her, holding the door for her. Why can’t you do that?” “Are you insane?” he responded. “I barely know the woman!” ",
    "I was sitting on the back porch with my wife when I suddenly blurted out, “I love you.” “Is that you or the beer talking?” she asked. I answered, “It’s me… talking to my beer.” ",
    "“Siri,” I asked my phone, \"why am I so bad with women?\" She responded, \"I’m Bixby, you moron.\"",
    "My wife and I were out to dinner and the waitress started flirting with me. \"She obviously has COVID,\" my wife said. \"Why?\" I asked. \"Because she has no taste.\"",
    "Marriage involves three rings: The engagement ring, the wedding ring, and the suffer-ring. ",
    "\"Your wife and daughter look like twins,\" my friend said. \"Well,\" I replied, \"they were separated at birth.\"",
    "One friend complained to another, “All my husband and I do anymore is fight. I've been so upset, I’ve lost 20 pounds.” “If it’s that bad, why don’t you just leave him?” asked the second friend. “I’d like to lose another fifteen pounds first.” ",
    "I bought Spotify premium for an uninterrupted music experience. But I still hear my wife’s bickering between songs.",
    "I can always tell when my wife is lying just by looking at her. I can also tell when she’s standing. ",
    "My wife told me that I twist everything she says to my advantage. I take that as a compliment. ",
    "My ex and I had a very amicable divorce. I know this because when I posted on Facebook, “I’m getting a divorce,” she was the first one to like it.",
    "My wife and I have decided not to have kids. The kids are taking it pretty badly.",
    "When does a joke become a dad joke? When it becomes apparent.",
    "My daughter just shrieked at me, “Daaaaaad, you haven’t listened to a word I’ve said, have you?” What an odd way to begin a conversation. ",
    "I have a great joke about nepotism. But I’ll only tell it to my kids.",
    "“Dad, can you explain to me what a solar eclipse is?” No sun.",
    "What happened when the ten-year-old cannibal spilled his soup? His mother gave him an earful.",
    " I’d like to have kids one day. I don’t think I could stand them any longer than that, though.",
    "What did the buffalo say to his son when he dropped him off at school? Bison.",
    "I wonder what my parents did to fight boredom before the internet. I asked my eighteen brothers and sisters but they didn’t have any idea either. ",
    "My parents raised me as an only child. Which really annoyed my younger brother.",
    "I tell dad jokes but I have no kids. I’m a faux pa!",
    "A kid decided to burn his house down. His dad watched, tears in his eyes. He put his arm around the mom and said, “That’s arson.”",
    "Today I decided to go visit my childhood home. I asked the residents if I could come inside because I was feeling nostalgic, but they refused and slammed the door on my face. My parents are the worst. ",
    "“What’s your name, son?” The principal asked his student. The kid replied, “D-d-d-dav-dav-david, sir.” “Do you have a stutter?” the principal asked. The student answered, “No sir, my dad has a stutter but the guy who registered my name was a real jerk.” ",
    "Concerned that his son was spending too much time on video games, a dad told him, “When Abe Lincoln was your age, he was studying books by the light of the fireplace.” “Oh yeah?” the son retorts. “Well, when Abe Lincoln was your age, he was President of the United States.” ",
    "A father tells his son that he was adopted. “I want to meet my biological parents,” the son demands. “We are your biological parents,” the father responds. “Now pack up, the new ones will pick you up in twenty minutes.”",
    "A son tells his father, “I have an imaginary girlfriend.” The father sighs and says, “You know, you could do better.” “Thanks Dad,” the son says. “That means a lot.” The father shakes his head and goes, “I was talking to your girlfriend.” ",
    "Yesterday, I was washing the car with my son. He said, “Dad, can’t you just use a sponge?” ",
    "My dad died because he couldn’t remember his blood type. He kept insisting we “be positive,” but it’s just so hard without him. ",
    "I tried to explain to my 4-year-old son that it’s perfectly normal to accidentally poop your pants. But he’s still making fun of me. ",
    "I wasn’t close to my father when he died. Which is lucky because he stepped on a landmine.",
    // jokes from https://www.fatherly.com/life/dad-jokes
    "Why can’t a leopard hide?\nBecause he’s always spotted.",
    "How do moths swim?\nUsing the butterfly stroke.",
    "What do you call an illegally parked frog?\nToad.",
    "How many tickles does it take to make an octopus laugh?\n10 tickles.",
    "Do you know the story about the chicken that crossed the road?\nMe neither, I couldn’t follow it.",
    "What do you get from a pampered cow?\nSpoiled milk!",
    "Why are spiders so smart?\nThey can find everything on the web.",
    "How can a leopard change his spots?\nBy moving.",
    "What did the duck say when it bought chapstick?\n“Put it on my bill!”",
    "What does a cow use to do math?\ncow-culator.",
    "What would bears be without the letter B?\nEars.",
    "What is a dolphin’s favorite country?\nFinland",
    "Why did the fish run wild?\nIt found its sense of porpoise.",
    "Can a kangaroo jump higher than the Empire State Building?\nOf course! Buildings can’t jump, silly.",
    "What did the alpaca say to his date?\n“Want to go on a picnic? Alpaca lunch.”",
    "What do you get if you cross an angry sheep with a moody cow?\nn animal that’s in a baaaaaaaaad moooooooood.",
    "Why do seagulls fly over the sea?\nIf they flew over the bay, they’d be called bagels.",
    "What do you call a penguin in the White House?\nLost.",
    "What do you call a kangaroo’s lazy joey?\npouch potato.",
    "Why are snails bad at racing?\nThey’re sluggish.",
    "How does a boar sign its name?\nWith a pig pen.",
    "Why should you never trust a carp’s excuse?\nThey always seem a little fishy.",
    "Where do baby cats learn to swim?\nThe kitty pool.",
    "Which is faster, hot or cold?\nHot, because you can catch a cold.",
    "What’s brown and sounds like a bell?\nDung!",
    "Why did the sun let off a massive explosion?\nIt was star-tled.",
    "What did the photon say when asked if she needed to check a bag?\n“No thanks, I’m traveling light!”",
    "Did you hear that I’m reading a book about anti-gravity?\nIt’s impossible to put down.",
    "Did you know milk is the fastest liquid on earth?\nIt’s pasteurized before you even see it.",
    "What did one ocean say to the other ocean?\nNothing, they just waved.",
    "What kind of music do the planets listen to?\nNep-tunes!",
    "Why did everyone enjoy being around the volcano?\nIt’s just so lava-ble.",
    "How do you organize a space party?\nYou planet.",
    "What did the big flower say to the tiny flower?\n“Hey there bud!”",
    "Why are skeletons so calm?\nBecause nothing gets under their skin.",
    "What did Mars ask Saturn?\n“Hey, why don’t you give me a ring some time?”",
    "Why can’t you trust an atom?\nBecause they make up everything.",
    "Did you hear about the quantum brush?\nIt’s always leaving hair entangled.",
    "Why shouldn’t you make fun of a paleontologist?\nBecause you will get Jurasskicked.",
    "What do clouds do when they become rich?\nThey make it rain!",
    "Want to hear a potassium joke?\nK.",
    "Why are helium, curium, and barium the medical elements?\nBecause if you can’t heal-ium or cure-ium, you bury-um.",
    "How did the chemist feel about oxygen and potassium hanging out?\nOK.",
    "When Silver Surfer and Iron Man team up, what do you call them?\nlloys.",
    "Why didn’t the melons get married?\nBecause they cantaloupe.",
    "What do you call a fake noodle?\nn impasta.",
    "What did the Baby corn ask Mama corn?\n“Where’s my pop corn?”",
    "Why couldn’t the sesame seed get off the hill?\nIt was on a roll.",
    "What’s the holiest of breads?\nbagel.",
    "What kind of egg did the evil chicken lay?\ndeviled egg.",
    "Why did the onion get flustered?\nIt saw the salad dressing.",
    "Why is the hot pepper the nosiest vegetable?\nIt can’t help but get jalapéno space.",
    "Why do crabs never share their lobsters?\nThey’re shellfish.",
    "What do Japanese monsters like to eat ?\nRaw-men",
    "Why are mushrooms always invited to parties?\nThey’re a fungi.",
    "What do you call a fancy seafood meal?\nSo-fish-ticated.",
    "What do you call a sad strawberry?\nblueberry.",
    "Why did the banana go to the hospital?\nHe wasn’t peeling well.",
    "What do you call a pig that knows karate?\npork chop.",
    "Where do pancakes rise?\nIn the yeast.",
    "What is a mummy’s favorite food?\nWraps.",
    "What kind of fruit do you bring while sailing?\nNaval oranges.",
    "What do frogs order at restaurants?\nFrench flies.",
    "What do you call a fake noodle?\nImpasta.",
    "What’s orange and sounds like a parrot?\ncarrot.",
    "How do I look?\nWith your eyes.",
    "How do you get a country girl’s attention?\ntractor.",
    "Why is the cemetery so popular?\nPeople are just dying to get in there!",
    "What was the child who wouldn’t nap guilty of?\nResisting a rest!",
    "Where do cows go for entertainment?\nTo the moovies.",
    "What did the zero say to the eight?\n“Nice belt.”",
    "What do you call a pile of cats?\nmeow-tain.",
    "What do you call a flea in France?\nparis-ite.",
    "What runs around a baseball field but never moves?\nfence.",
    "Why was the calendar afraid?\nIts days were numbered.",
    "What time did the man go to the dentist?\nTooth hurt-y.",
    "Why didn’t the skeleton climb the mountain?\nIt didn’t have the guts.",
    "How do you make a tissue dance?\nYou put a little boogie in it.",
    "My dad told me a joke about boxing.\nI guess I missed the punch line.",
    "What kind of car does an egg drive?\nyolkswagen.",
    "What does a cat say both before and after dinner?\nMeow",
    "What’s the difference between a snowman and a snow woman?\nSnowballs.",
    "Did you hear about the man who fell into an upholstery machine?\nHe’s fully recovered.",
    "Why did the coach go to the bank?\nTo get his quarter back.",
    "What did the fisherman say to the magician?\n“Pick a cod, any cod.”",
    "Which bear is the most condescending?\npan-duh!",
    "What kind of noise does a witch’s vehicle make?\nBrrrroooom, brrroooom.",
    "What does a baby computer call his father?\nData.",
    "Why was the robot so tired after his road trip?\nHe had a hard drive.",
    "Did you hear about the power outlet that got into a fight with a power cord?\nHe thought he could socket to him.",
    "Why did the computer have no money left?\nSomeone cleaned out its cache!",
    "What’s a computer’s favorite snack?\nMicrochips!",
    "What do you call monkeys with a shared Amazon account?\nPrime mates.",
    "Why should you never use “beef stew” as a password?\nIt’s not stroganoff.",
    "What do you call your grandma’s number on speed dial?\nInstagram.",
    "What’s another name for an iPhone power cord?\npple juice.",
    "What do you call a video game rematch?\nWii-match.",
    "What do you call a TV vaccination?\nscreen-shot.",
    "Why did the PowerPoint presentation cross the road?\nTo get to the other slide.",
    "How do ghosts find answers?\nThey Boo-gle it.",
    "Why did the computer always play “Someone Like You?”\nIt was a Dell.",
    "What’s the world most tiresome chatbot?\nChatZZZ",
    "Why did the laptop show up late to school?\nIt had a hard drive.",
    "What kind of internet page do you seek out when your eyes are tired of reading?\nsite for sore eyes.",
    "What do you call an iPhone with no sense of humor?\nToo Siri-ous.",
    "Why was the Samsung phone’s camera blurry?\nIt had lost its contacts.",
    "Why was the man fired from the keyboard factory?\nHe wasn’t working with enough shifts.",
    "Why couldn’t the computer buy a new pair of jeans?\nIt had spent all its cache.",
    "Why do smartphones ring?\nBecause they can’t talk.",
    "How do you follow Will Smith in the snow?\nYou follow the fresh prints.",
    "How do celebrities stay cool?\nThey have many fans.",
    "What do you call it when Batman skips church?\nChristian Bale.",
    "What’s the difference between Harry Potter and Voldemort’s Instagram accounts?\nVoldemort has followers, Harry Potter, friends.",
    "What’s Forrest Gump’s Facebook password?\n1forest1.",
    "Why does Snoop Dogg always carry an umbrella?\nFo’ drizzle.",
    "What do you call a security guard outside of a Samsung store?\nGuardians of the Galaxy.",
    "What did Mark Wahlberg feed Ted?\nNothing, because he was already stuffed.",
    "Why can’t you give Elsa a balloon?\nBecause she’d just let it go.",
    "How does Reese eat cereal?\nWitherspoon.",
    "What do you get when you light 16 candles under a romantic comedy lead actor?\nJohn Bar-be-Cusak.",
    "What do you call a nearsighted cowboy?\nSquint Eastwood.",
    "What do you call a slightly tipsy actor stuck in a zombie TV show?\nPedro Mescal",
    "Why did the Jedi cross the road?\nTo get to the dark side.",
    "Did you hear about the new Johnny Depp movie?\nIt’s rated “Arrrrrrr.”",
    "What kind of business would Yoda start?\nToy Yoda dealership",
    "What do Gungans keep things in?\nJar Jars.",
    "What is Jabba the Hutt’s middle name?\nThe!",
    "How did Darth Vader know what Luke was getting for his birthday?\nHe felt his presents.",
    "What do you call Chewbacca when he has chocolate stuck in his fir?\nchocolate chip Wookie.",
    "Which Star Wars character works at a restaurant?\nDarth Waiter!",
    "Where did Luke Skywalker buy his new arm?\nt the second hand store!",
    "What does everyone call Darth Vader whenever he procrastinates?\nDarth Later.",
    "What was Luke’s reaction to food made by baby Wookiees?\n“It’s good, but it’s a little Chewie.”",
    "Did you hear about the Gungan who became a taxi cab driver?\nHis name is Car Car Binks.",
    "Why does Darth Vader always sound so angry when he breathes?\nHe’s always venting.",
    "What do you call Kenobi triplets?\nObi-Threes.",
    "What do you call C-3PO when he’s being a good listener?\nHear-Threepio.",
    "What was Luke’s secret codename before he got his mechanical limb?\nHand Solo",
    "Where would Darth Vader stay if he would settle down in the USA?\nThe Empire State Building.",
    "Why did the movies come out 4, 5, 6, 1, 2, 3?\nIn charge of scheduling, Yoda was.",
    "Why does Princess Leia keep her hair tied up in buns?\nSo it doesn't Hang So-low.",
    "How often did my friend ride his DeLorean?\nFrom time to time.",
    "What’s worse than raining cats and dogs?\nHailing taxis.",
    "What do you get when dinosaurs crash their cars?\nTyrannosaurus wrecks.",
    "What do you get when you put a car and a pet together?\ncarpet.",
    "Why did the cop pull over the U-Haul van?\nHe wanted to bust a move.",
    "What do you call a Ford Fiesta that ran out of fuel?\nThe Ford Siesta.",
    "What kind of vehicle does an egg drive?\nYolks-wagen.",
    "What did the traffic light say to the car?\n“Close your eyes, I’m changing!”",
    "Why can’t motorcycles do push-ups?\nBecause they’re always two-tired.",
    "What kind of cars do cats drive?\nCatillacs.",
    "What happened when the man crashed his expensive car?\nHe found out how a Mercedes bends.",
    "Why did the spider buy a sports car?\nSo he could take it out for a spin.",
    // jokes from https://www.today.com/life/dad-jokes-rcna27325
    "Two fish are in a tank. One turns to the other and says, “Any idea how to drive this thing?”",
    "I don't tell dad jokes that often. But when I do, he laughs.",
    "Why does a chicken coop only have two doors? Because if it had four it would be a sedan.",
    "What did the pirate say on his birthday? “Aye, matey!”",
    "I was going to tell a sodium joke, then I thought, “Na.”",
    "What's a witch's favorite subject in school? Spelling.",
    "Why are frogs good at baseball? They know how to catch fly balls.",
    "What's the easiest building to lift? A lighthouse.",
    "Why do sweaters tend to hang out together? They're pretty close-knit.",
    "What’s the best way to get the hospital after breaking your foot? Tow truck.",
    "Did you hear about the archeologist that got fired? His career is in ruins.",
    "What did the buffalo say to her son on the first day of school? “Bison.”",
    "Why do ducks have feathers on their tales? To hide their butt-quacks.",
    "Why shouldn't you tell secrets in a cornfield? There are too many ears around.",
    "What kind of underpants do lawyers wear? Briefs.",
    "What do you call it when a cow grows facial hair? A moo-stache.",
    "Did you hear about the two rowboats that got into an argument? It was an oar-deal.",
    "Did you hear about the cleaners who went to space? They ended up scrubbing the mission.",
    "What did the beach say when the tide came in? Long time no sea.",
    "Why do turkeys play percussion? They have drumsticks.",
    "I adopted a dog from a blacksmith. As soon as I brought him home, he made a bolt for the door.",
    "How much does it cost to swim with sharks? An arm and a leg.",
    "What did one toilet say to the other? You appear a bit flushed.",
    "Why are most people tired on April 1? They've just finished a 31-day March.",
    "How do you make a tissue dance? Put a little boogie in it.",
    "Why did the rabbit go to the salon? It was having a bad hare day.",
    "Where do birds stay when they travel? Someplace cheep.",
    "What should you do if your puppy isn't feeling well? Take him to the dog-tor.",
    "Why can't leopards play hide-and-seek? Because they're always spotted.",
    "What kind of felines can bowl? Alley cats.",
    "Why did the man bring his watch to the bank? He wanted to save time.",
    "Where do penguins go to vote? The North Poll.",
    "How do you make a robot angry? Keep pushing his buttons.",
    "What's the best way to make a bandstand? Take away their chairs.",
    "How do you light up a sports stadium? With a soccer match.",
    "Did you hear about the kidnapping at school? They woke him up.",
    "I told a bad chemistry joke once. I got no reaction.",
    "Why did the cow go to Hollywood? To be in the moo-vies.",
    "Did you hear about the cat that ate a lemon? Now it’s a sour puss.",
    "How do mice floss their teeth? With string cheese.",
    "What do you call a happy cowboy? A jolly rancher",
    "What did one wall say to the other? I’ll meet you at the corner.",
    "What do clouds wear beneath their pants? Thunderwear.",
    "What kind of bagel can travel? A plain bagel.",
    "When's the best time to call your dentist? Tooth-hurty.",
    "What's the best way to catch a fish? Ask someone to throw it to you.",
    "What do you call an anxious fly? A jitterbug.",
    "How did the piano get locked out of its car? It lost its keys.",
    "Why did the orchestra get struck by lightning? It had a conductor.",
    "What do you call a fake dad? A faux pas.",
    "How do you make an eggroll? You push it.",
    "I've never been a fan of facial hair. But now it's starting to grow on me.",
    "Did you hear about the fire at the shoe factory? Many soles were lost.",
    "What kind of fish knows how to do an appendectomy? A Sturgeon.",
    "How do you hire a horse? Put up a ladder.",
    "Why did the pony ask for a glass of water? Because it was a little horse.",
    "Is there anything worse than when it's raining cats and dogs? Yes, hailing taxis.",
    "How many apples can you grow on a tree? All of them.",
    "My manager told me to have a good day. So I didn't go into work.",
    "What do kids play when they have nothing else to do? Bored games.",
    "What kind of music do elves listen to? Wrap music.",
    "Why aren’t lobsters generous? Because they’re shellfish.",
    "Where do sheep go on vacation? The Baaaa-hamas.",
    "Where did people hang out during medieval times? At knight clubs.",
    "Why did the employee go work in stilts? He wanted a raise.",
    "What do cake and baseball have in common? They both need a batter.",
    "When does Friday come before Thursday? In the dictionary.",
    "What did the tree say when spring finally arrived? What a re-leaf.",
    "How can you tell if a pig is hot? It's bacon.",
    "Did you hear about the guy who afraid of hurdles? He got over it.",
    "Why did the drum go to bed? It was beat.",
    "What do you call a rude cow? Beef jerky.",
    "Did you hear about the guy who drank invisible ink? He's at the hospital waiting to be seen.",
    "How do you get a squirrel's attention? Act like a nut.",
    "What did one volcano say to the other? I lava you.",
    "Why did the computer catch cold? It left a window open.",
    "How do you cook an alligator? With a croc-pot.",
    "What did the earthquake say when it was done? Sorry, my fault!",
    "Why did the computer go to bed? It needed to crash.",
    "What do you give the dentist of the year? A little plaque.",
    "What causes dry skin? A towel.",
    "I went to buy a pair of camouflage pants, but I couldn’t find any.",
    "How can you tell when a comic passes gas? Something smells funny.",
    "What kind of bug can tell time? A clock-roach.",
    "Why shouldn’t you trust trees? They seem shady.",
    "What do lawyers wear to work? Law suits.",
    "What do you call a can opener that doesn't work? A can't opener.",
    "What do pigs use to clean up? Hogwash.",
    "What's a pirate's favorite letter? You'd think it's the \"R,\" but it's really the \"C.\"",
    "What's a zebra? A couple sizes bigger than an A.",
    "Did you hear about the bossy man at the bar? He ordered everyone around.",
    "Did you hear about the broken guitar for sale? It comes with no strings attached.",
    "I wanted to take a bath, but decided to leave it where it is.",
    "A horse walks into a bar. The bartender says, \"Why the long face?\"",
    "Why'd the roofer go to the doctor? He had shingles.",
    "Did you hear about the woman who couldn't stop collecting magazines? She had issues.",
    "Humpty Dumpty had a great fall. Summer wasn’t too bad either.",
    "What do you call a fish with no eyes? Fsh.",
    "What should you do if you meet a giant? Use big words.",
    "What do you call a cow with two legs? Lean beef.",
    "What sits on the seabed and has anxiety? A nervous wreck.",
    "What do you call a man wearing a rug on his head? Matt.",
    "What’s the best air to breathe if you want to be rich? Millionaire.",
    "Why did the girl toss a clock out the window? She wanted to see time fly.",
    "Once I read a book about glue. I couldn’t put it down.",
    "Where do armies belong? In your sleevies.",
    "What did one plate say to another plate? Tonight, dinner's on me.",
    "Did you hear about the king that went to the dentist? He needed to get a crown.",
    "What happens when doctors get frustrated? They lose their patients.",
    "What do you call a bear with no teeth? A gummy bear.",
    "Why did the coach go to the bank? To get his quarter back.",
    "Why do nurses like red crayons? Sometimes they have to draw blood.",
    "What kind of jewelry do rabbits wear? 14 carrot gold.",
    "What do you call a cheese that isn’t yours? Nacho cheese!",
    "What did the janitor say when he jumped out of the closet? Supplies!",
    "Why did the girl bring a ladder on the bus? She wanted to go to high school.",
    "Why did the golfer bring two pairs of pants? Just in case he got a hole in one.",
    "Why did the cowboy adopt a wiener dog? He wanted to get a long little doggie.",
    "Have you ever had a bad sausage? It’s the wurst.",
    "What’s more unbelievable than a talking dog? A spelling bee.",
    "What do you call a cow with no legs? Ground beef.",
    "How do you fix a broken tomato? With tomato paste.",
    "Why did the orange stop halfway across the road? It ran out of juice.",
    "Why did the Oreo go to the dentist? It lost its filling.",
    "Why did the whale blush? It saw the ocean’s bottom.",
    "How do you get an astronaut’s baby to stop crying? You rocket.",
    "Why shouldn't you play poker in the jungle? Too many cheetahs.",
    "What sounds like a sneeze and is made of leather? A shoe.",
    "How do you stop a bull from charging? You cancel its credit card.",
    "Why was the math book sad? It had too many problems.",
    "Why are fish so smart? Because they swim in schools.",
    "Why did the employee get fired from the keyboard factory? He wasn’t putting in enough shifts.",
    "Did you hear about the man who cut off his left leg? He’s all right now.",
    "Did you hear the one about the claustrophobic astronaut? He just needed a little space.",
    "What kind of music should you listen to while fishing? Something catchy!",
    "What do you call a girl in the middle of a tennis court? Annette.",
    "What did the ocean say to the beach? Nothing. It just waved.",
    "Why did the nose feel sad? It was always getting picked on.",
    "Why did the deer go to the dentist? It had buck teeth.",
    "A cheese factory exploded in France. Da brie is everywhere!",
    "Where does a sheep go to get a haircut? The baa baa shop.",
    "Why did the poodle buy a clock? It wanted to be a watch dog.",
    "What did the mama cow say to the baby cow? It’s pasture bed time.",
    "Why should you never use a dull pencil? Because it’s pointless.",
    "Why did the cookie go to the doctor? It was feeling crumby.",
    "Where did the cat go after losing its tail? The retail store.",
    "What kind of sandals do frogs wear? Open-toad.",
    "What do you call a herd of sheep falling down a hill? A lambslide.",
    "How do you organize a space party? You planet.",
    "How many tickles does it take to make an octopus laugh? Ten-tickles.",
    "What do you call a potato wearing glasses? A spec-tater.",
    "What do you call a moose with no name? Anonymoose.",
    "Why did the ram run over the cliff? He didn’t see the ewe turn.",
    "Why did the picture go to jail? He was framed.",
    "What is a calendar’s favorite food? Dates.",
    "Why do bananas wear sunscreen? Because they peel.",
    "Why do bees have sticky hair? Because they use honey combs.",
    "Why did the watch go on vacation? To unwind.",
    "When is a door not a door? When it’s ajar.",
    "How does a penguin build a house? Igloos it together.",
    "Why do melons have weddings? Because they cantaloupe.",
    "Why did the computer get glasses? To improve its website.",
    "What did the blanket say to the bed? I’ve got you covered.",
    "What did the roof say to the shingle? The first one’s on the house.",
    "What do you call birds that stick together? Velcrows",
    "Why did the duck fall on the sidewalk? He tripped on a quack.",
    "How do birds learn to fly? They wing it.",
    "Did you hear about the walnut and cashew that threw a party? It was nuts.",
    "Did the hear about the ice cream truck accident? It crashed on a rocky road.",
    "What kind of bird works on a construction site? A crane.",
    "What did one elevator say to the other elevator? I think I’m coming down with something.",
    "What did the hamburger name its baby? Patty.",
    "How much money does a skunk have? Just one scent.",
    "How did the barber win the race? He knew a shortcut.",
    "What type of music do the planets enjoy? Neptunes.",
    "Why did the phone wear glasses? Because it lost all its contacts.",
    "Why do bakers work so hard? Because they knead dough.",
    "Why are fish so easy to weigh? Because they have their own set of scales.",
    "What do you call a priest that becomes a lawyer? A father-in-law.",
    "What do you give a scientist with bad breath? Experi-mints.",
    "What did Benjamin Franklin say when he discovered electricity? Nothing. He was too shocked.",
    "What do you call a medieval lamp? A knight light.",
    "What did one hat say to the other? You go on ahead.",
    "Why did the frog take the bus to work? His car got toad.",
    "What does an evil hen lay? Deviled eggs.",
    "How can you tell the difference between a dog and tree? By their bark.",
    "Why do dragons sleep during the day? Because they like to fight knights.",
    "Why did the scarecrow win an award? It was outstanding in its field.",
    "Did you hear about the 12-inch dog? It was a foot long.",
    "Why did the baseball player get arrested? He stole third base.",
    "What did one piece of tape say to the other? Let’s stick together.",
    "What's brown and sticky? A stick.",
    "How does the rancher keep track of his cattle? With a cow-culator.",
    "What do you call a shoe made out of a banana? A slipper.",
    "How you fix a broken pumpkin? With a pumpkin patch.",
    "Where do boats go when they’re sick? To the dock.",
    "Can February March? No, but April May!",
    "What do you call a fibbing cat? A lion.",
    "Did you hear the rumor about butter? Well, I’m not going to go spreading it!",
    "What’s a scarecrow’s favorite fruit? Straw-berries",
    "Where do burgers go dancing? At the meatball.",
    "What time do ducks wake up? At the quack of dawn.",
    "Why was the broom late? It over-swept.",
    "What kind of tree fits in your hand? A palm tree.",
    "Where do books hide when they’re afraid? Under their covers.",
    "How do trees get on the internet? They log in.",
    "What does a painter do when he gets cold? Puts on another coat.",
    "What did the calculator say to the pencil? You can count on me.",
    "What has four wheels and flies? A garbage truck.",
    "What do cows like to read? Cattle-logs.",
    "How did the farmer fix his torn overalls? With a cabbage patch.",
    "What do you get when you cross an elephant and a fish? Swimming trunks.",
    "What kind of cereal do leprechauns eat? Lucky Charms.",
    "What do you call recently-married spiders? Newly-webs.",
    "Where do crayons go on vacation? Color-ado.",
    "Why can’t you trust a balloon? It’s full of hot air.",
    "What do you get when you cross a Smurf and a cow? Blue cheese.",
    "What happens when ice cream gets angry? It has a meltdown.",
    "How do celebrities keep cool? They have many fans.",
    "What do you call a locomotive carrying bubble gum? A chew chew train.",
    "How do you get a mouse to smile? Say “cheese.”",
    "Why couldn’t the bike stand up on its own? It was two-tired.",
    "What do you call a sheep that knows karate? A lamb chop.",
    "Why did the snowman buy a bag of carrots? He wanted to pick his nose.",
    "What did the Dalmatian say after dinner? That hit the spot.",
    "How do you know when a bike is thinking? You can see its wheels turning.",
    "What does a librarian use to go fishing? A bookworm.",
    "What did one leaf say to the other? I’m falling for you.",
    "Where’s the one place you should never take your dog? A flea market.",
    "How does Darth Vader like his bagels? On the dark side.",
    "What do you call spaghetti in disguise? An impasta.",
    "Where do elephants store luggage? In a trunk.",
    "Why do birds fly south? Because it’s too far to walk.",
    "What do you call a fly with a sore throat? A hoarse fly.",
    "Dogs can’t operate MRI machines — but cats-can.",
    "Where do you learn to make ice cream? Sundae school.",
    "If you see a robbery at an Apple store, does that make you an iWitness?",
    "I had a date last night. It was perfect. Tomorrow, I’ll have a grape.",
    "Justice is a dish best served cold. If it were served warm, it would be just-water.",
    "It was an emotional wedding — even the cake was in tiers.",
    "Why did Waldo go to therapy? To find himself.",
    "I have an inferiority complex, but it’s not a very good one.",
    "Our vacuum cleaner is getting old. It's just gathering dust.",
    "Why did the thief take a shower before robbing the bank? He wanted to make a clean getaway.",
    "Why was the traffic light late to work? It took too long to change.",
    "Why do hamburgers go south for the winter? So they don’t freeze their buns.",
    "Why didn’t the sun go to college? It already had a million degrees.",
    "What do you call someone who can’t stick to a diet? A desserter.",
    "Why did the little strawberry cry? His mom was in a jam.",
    "Why couldn’t the toilet paper cross the road? It got stuck in a crack.",
    "What do you get from a pampered cow? Spoiled milk.",
    "Getting paid to sleep would be my dream job.",
    "I used to be a banker, but I lost interest.",
    "Why can’t you trust an atom? Because they make up everything.",
    "Why did the tomato blush? It saw the salad dressing.",
    "I haven’t talked to my wife in a week — I didn’t want to interrupt her.",
    "Why are pigs bad drivers? They hog the road.",
    "I’m so good at sleeping, I can do it with my eyes closed!",
    "Why did police arrest the turkey? They suspected fowl play.",
    "What do computers eat for a snack? Microchips.",
    "How do frogs invest their money? They use a stock croaker.",
    "Did you hear about the whale that swallowed a clown? It felt funny after.",
    "The past, present and future walked into a bar. It was tense.",
    "Why did the tailor get fired? He wasn’t a good fit.",
    "What do you call two ducks and a cow? Quackers and milk."
]
